version: "3.9"
services: 
  web:
    build: .
    ports:
      - "8000:3000"
    volumes:
      - .:/code
      - /code/node_modules
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'

